_target_: mf_gravitas.data.AlgorithmMetaFeatures
path: ${dataset.path.algo_meta}
index_col: 0 # pd.read argument

# the important part!
transforms:
  _target_: mf_gravitas.data.preprocessings.transformpipeline.TransformPipeline
  # path: some/path - we might want to automate and structure it
  modulelist:
    - _target_: mf_gravitas.data.preprocessings.nan_transforms.Zero_fill
    - _target_: mf_gravitas.data.preprocessings.table_transforms.Drop
      columns: # fixme: do not drop categorical features in algo meta features
        - num.impute.selected.cpo
        - respect.unordered.factors
        - splitrule
        - task_id

    - _target_: mf_gravitas.data.preprocessings.table_transforms.ToTensor
    - _target_: mf_gravitas.data.preprocessings.tensor_transforms.ScaleStd
