_target_: margret.data.algorithm_meta_features.AlgorithmMetaFeatures
path: ${dataset.path.algo_meta}
index_col: 0 # pd.read argument

# the important part!
transforms:
  _target_: margret.data.preprocessings.transformpipeline.TransformPipeline
  # path: some/path - we might want to automate and structure it
  modulelist:
    - _target_: margret.data.preprocessings.table_transforms.Drop
      columns: # fixme: do not drop categorical features in algo meta features
        - learner
        - ranger.replace
        - ranger.respect.unordered.factors
        - ranger.splitrule
        - xgboost.booster
        - task_id
    - _target_: margret.data.preprocessings.nan_transforms.Zero_fill
    - _target_: margret.data.preprocessings.table_transforms.ToTensor
    - _target_: margret.data.preprocessings.tensor_transforms.ScaleStd
