trainerobj:
  _target_: imfas.trainer.BaseTrainer
  optimizer:
    _partial_: true
    _target_: torch.optim.Adam
    lr: 0.001

run_call:
  epochs: 1000

  train_loss_fn:
    _target_: imfas.losses.ranking_loss.SpearmanLoss
#    reduction: 'mean'
#    ranking_fn: torchsort.soft_rank
#    ts_kwargs: { }
#
#  valid_loss_fns:
#    Spearman: # Name for wandb, can specify other losses in dict format!
#      _target_: imfas.losses.ranking_loss.SpearmanLoss
#      reduction: 'mean'
#      ranking_fn: torchsort.soft_rank
#      ts_kwargs: { }
