trainerobj:
  _target_: imfas.trainer.BaseTrainer
  optimizer:
    _partial_: true
    _target_: torch.optim.Adam
    lr: 0.001

run_call:
  epochs: 2
  log_freq: 2

  train_loss_fn: Null

  valid_loss_fns: Null

  test_loss_fns: Null