trainerobj:
  _target_: imfas.trainer.no_opt.NoOptTrainer


run_call:
  epochs: 1 # This must be 1, because the model can only be evaluated on a single fidelity and only once
  log_freq: 5         # wandb mistakes single value additions as media files, so log_freq helps mitigate that
  
  valid_loss_fns:
      top1_regret:
        _target_: imfas.evaluation.topk_regret.TopkMaxRegret
        k: 1