defaults:
  - /trainer/basetrainer@_here_ # specialize the basetrainer!
  - _self_


trainerobj:
  _target_: imfas.trainer.sh_budget_trainer.SHBudgetTrainer
  sh_model:
    _target_: imfas.models.baselines.successive_halving.SuccessiveHalving
    eta: 2
    budgets: ${dataset.slices}
