trainerobj:
  _target_: imfas.trainer.slice_evaluator.SliceEvaluatorSH # TO AVOID training
  masking_fn:
    _target_: imfas.data.dataset_join.dataset_join_Dmajor.mask_lcs_to_max_fidelity
    _partial_: True
  max_fidelities: [ 2, 10 ] #  indices on refer to base.slice fidelities (in lcbench case)


run_call:
  epochs: 1 # since we only need a single test execution anyways (HACK)

  train_loss_fn: None
  valid_loss_fns:
    spearman:
      _target_: imfas.losses.spearman.SpearmanLoss # Fixme: replace this with