steps: 10  # granularity


evaluator:
  _target_: imfas.evaluation.optimal_rankings.ZeroShotOptimalDistance
  ranking_loss:
    _target_: sklearn.metrics.ndcg_score
  batch: 20
  scaler: 
    _target_: sklearn.preprocessing.MinMaxScaler