trainerobj:
  _target_: imfas.trainer.slice_evaluator.SliceEvaluator # TO AVOID training
  masking_fn:
    _target_: imfas.data.dataset_join.dataset_join_Dmajor.mask_lcs_to_max_fidelity
    _partial_: True
  max_fidelities: ${dataset.slices} #  indices on refer to base.slice _fidelities (in lcbench case)


run_call:
  epochs: 0 # since we only need a single test execution anyways (HACK)
  log_freq: 0
  train_loss_fn: null
  valid_loss_fns: null
  test_loss_fns:
    spearman:
      _target_: imfas.losses.spearman.SpearmanLoss # Fixme: replace this with