wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1650619523
    t:
      1:
      - 1
      - 5
      - 50
      - 53
      - 55
      2:
      - 1
      - 5
      - 50
      - 53
      - 55
      3:
      - 14
      - 16
      4: 3.9.7
      5: 0.12.14
      8:
      - 5
command:
  desc: null
  value: 'main.py '
dataset:
  desc: null
  value: lcbench
dataset_raw:
  desc: null
  value: lcbench
evaluation:
  desc: null
  value: optimal_rankings
lr:
  desc: null
  value: 0.002
model:
  desc: null
  value: autoencoder
num_competitors:
  desc: null
  value: 2
num_workers:
  desc: null
  value: 2
output_dir:
  desc: null
  value: ./tmp
seed:
  desc: null
  value: 0
shuffle:
  desc: null
  value: true
slurm_id:
  desc: null
  value: null
test_batch_size:
  desc: null
  value: 20
train_batch_size:
  desc: null
  value: 4
training:
  desc: null
  value: sequential
wandb:
  desc: null
  value:
    entity: tnt
    group: null
    id: null
    job_type: train
    mode: online
    notes: null
    project: gravitas
    resume: allow
    save_code: false
    sync_tensorboard: false
    tags: []
