wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1653313647
    t:
      1:
      - 1
      - 5
      - 50
      - 53
      - 54
      - 55
      3:
      - 14
      - 16
      4: 3.9.7
      5: 0.12.14
      8:
      - 5
command:
  desc: null
  value: main.py +experiment=lstm_yahpo
dataset:
  desc: null
  value:
    algo_meta:
      _target_: mf_gravitas.data.AlgorithmMetaFeatures
      index_col: 0
      path: ../../../../data/raw/yahpo/rbv2_svm/config_subset.csv
      transforms:
        _target_: mf_gravitas.data.preprocessings.transformpipeline.TransformPipeline
        modulelist:
        - _target_: mf_gravitas.data.preprocessings.nan_transforms.Zero_fill
        - _target_: mf_gravitas.data.preprocessings.table_transforms.Drop
          columns:
          - kernel
          - num.impute.selected.cpo
        - _target_: mf_gravitas.data.preprocessings.table_transforms.ToTensor
        - _target_: mf_gravitas.data.preprocessings.tensor_transforms.ScaleStd
    dataset_meta:
      _target_: mf_gravitas.data.DatasetMetaFeatures
      index_col: 0
      path: ../../../../data/raw/yahpo/rbv2_svm/meta_features.csv
      transforms:
        _target_: mf_gravitas.data.preprocessings.transformpipeline.TransformPipeline
        modulelist:
        - _target_: mf_gravitas.data.preprocessings.nan_transforms.Zero_fill
        - _target_: mf_gravitas.data.preprocessings.table_transforms.ToTensor
        - _target_: mf_gravitas.data.preprocessings.tensor_transforms.ScaleStd
    lc_meta:
      _target_: mf_gravitas.data.Dataset_LC
      metric: None
      path: ../../../../data/raw/yahpo/rbv2_svm/logs_subset.h5
      transforms:
        _target_: mf_gravitas.data.preprocessings.transformpipeline.TransformPipeline
        modulelist:
        - _target_: mf_gravitas.data.preprocessings.nan_transforms.Column_Mean
        - _target_: mf_gravitas.data.preprocessings.lc_slice.LC_TimeSlices
          slices:
          - 0.1
          - 0.2
          - 0.3
          - 0.4
          - 0.5
          - 0.6
          - 0.7
          - 0.8
          - 0.9
          - 1.0
    lc_metric: None
    metric: acc
    name: yahpo
    path:
      algo_meta: ../../../../data/raw/yahpo/rbv2_svm/config_subset.csv
      data_meta: ../../../../data/raw/yahpo/rbv2_svm/meta_features.csv
      lc_meta: ../../../../data/raw/yahpo/rbv2_svm/logs_subset.h5
    preprocessed_path: ../../../../data/raw/yahpo
    slices:
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
    - 0.6
    - 0.7
    - 0.8
    - 0.9
    - 1.0
    split: 0.8
dataset_raw:
  desc: null
  value:
    _target_: mf_gravitas.data.yahpo.raw_pipe.raw_pipe
    dataset_name: yahpo
    dir_data: ../../../data/
    enable: true
    selection:
      algo:
        _target_: smac.initial_design.latin_hypercube_design.LHDesign
        init_budget: 50
        rng:
          _target_: numpy.random.RandomState
          seed: 0
        ta_run_limit: 9999
      bench: rbv2_svm
      fidelity_type: trainsize
      metric: acc
      n_algos: 50
      noisy: false
      slices:
      - 0.1
      - 0.2
      - 0.3
      - 0.4
      - 0.5
      - 0.6
      - 0.7
      - 0.8
      - 0.9
      - 1.0
evaluation:
  desc: null
  value:
    evaluator:
      _target_: mf_gravitas.evaluation.optimal_rankings.ZeroShotOptimalDistance
      batch: 20
      ranking_loss:
        _target_: sklearn.metrics.ndcg_score
      scaler:
        _target_: sklearn.preprocessing.MinMaxScaler
    steps: 10
input_dim:
  desc: null
  value: 107
lr:
  desc: null
  value: 0.001
model:
  desc: null
  value:
    _target_: mf_gravitas.models.rank_lstm.RankLSTM_Ensemble
    lstm_layers: 2
    shared_hidden_dims:
    - 300
    - 200
n_algos:
  desc: null
  value: 50
num_competitors:
  desc: null
  value: 1
num_workers:
  desc: null
  value: 2
output_dir:
  desc: null
  value: ./tmp
seed:
  desc: null
  value: 0
shuffle:
  desc: null
  value: true
slurm_id:
  desc: null
  value: null
test_batch_size:
  desc: null
  value: 1
train_batch_size:
  desc: null
  value: 1
training:
  desc: null
  value:
    _target_: mf_gravitas.trainer.rank_trainer.train_lstm
    epochs: 100
    lr: 0.001
    test_lim: 5
wandb:
  desc: null
  value:
    entity: tnt
    group: yahpo_lstm
    id: null
    job_type: train
    mode: online
    notes: This is a run for mlp ranking ensemble
    project: gravitas
    resume: allow
    save_code: false
    sync_tensorboard: false
    tags: []
