_target_: imfas.models.hierarchical_transformer.HierarchicalTransformer

# TODO: @Difan please varify, that these are the correct parameters
input_dim_meta_feat: ${dynamically_computed.n_data_meta_features}
input_dim_algo_feat: ${dynamically_computed.n_algo_meta_features}
input_dim_lc: 1

d_model: 128
n_head: 4
dim_feedforward: 256
n_layers_lc: 2
n_layers_meta: 2
dropout: 0.2
output_dim: 1
norm_first: False
device: ${device}