_target_: imfas.models.imfas_transformer.IMFASHierarchicalTransformer

encoder:
  _target_: imfas.utils.mlp.MLP

  #  [ ${ dynamically_computed.n_data_meta_features }, 200, 100 ]
  activation: 'relu'
  hidden_dims:
    - ${ dynamically_computed.n_data_meta_features }
    - 300
    - 200

n_algos: ${dynamically_computed.n_algos}
n_fidelities: ${ dynamically_computed.len_lc }
n_layers: 2
has_reduce_layer: True

transformer_layer:
  _target_: torch.nn.TransformerEncoderLayer
  d_model: 64
  nhead: 4
  dim_feedforward: 128
  dropout: 0.2
  activation: 'relu'
  batch_first: True
  norm_first: True

decoder:
  _target_: imfas.utils.mlp.MLP

  #  [ ${ add: ${ model.encoder.hidden_dims[ 0 ] }, ${ transformer_dims[ 0 ] } }, 200, 100 ] # fixme: change index
  activation: 'relu'

  hidden_dims:
    # - ${add:dynamically_computed.n_algos,dynamically_computed.n_algos}
    - 264               # FIXME: dynamically compute based on the
    # concat dim before the tensor comes to the decoder
    - 1