# FIXME: make this dependent on the output from the raw transformation
name: LCBench
preprocessed_path: ../../../../data/raw/${dataset.name}  # fixme: is raw what we are going for?

path:
  algo_meta: ${dataset.preprocessed_path}/config_subset.csv
  data_meta: ${dataset.preprocessed_path}/meta_features.csv
  lc_meta: ${dataset.preprocessed_path}/logs_subset.h5

lc_metric: Train/val_accuracy # to be extracted & used (see dataset_raw/lcbench for options)
split: 0.8

slices: [ 20, 30, 51 ]