name: yahpo
preprocessed_path: ../../../../data/raw/${dataset.name}

path:
  algo_meta: ${dataset.preprocessed_path}/${dataset_raw.selection.bench}/config_subset.csv
  data_meta: ${dataset.preprocessed_path}/${dataset_raw.selection.bench}/meta_features.csv
  lc_meta: ${dataset.preprocessed_path}/${dataset_raw.selection.bench}/logs_subset.h5

base_dataset:
  _partial_: true # since split must be added # FIXME: continue here!
  _target_: mf_gravitas.data.Dataset_Join_Dmajor
  meta_dataset: dataset.dataset_meta
  lc: dataset.lc_meta
  #      meta_algo: dataset.algo_meta

# fixme: refactor this to be separately configurable at will for train/test
base_dataloader:
  _partial_: true # since split must be added # FIXME: continue here!
  _target_: torch.utils.data.DataLoader
  batch_size: ${test_batch_size}
  shuffle: False
  num_workers: ${num_workers}


split: 0.8

slices: [ 0.1, 0.3, 0.5, 1. ] #[ 1, 10, 20, 51 ] lcbench
metric: f1 # acc # Train/accuracy

# fixme: remove legacy
lc_metric: None
