name: yahpo
preprocessed_path: ../../../../data/raw/${dataset.name}

path:
  algo_meta: ${dataset.preprocessed_path}/${dataset_raw.selection.bench}/config_subset.csv
  data_meta: ${dataset.preprocessed_path}/${dataset_raw.selection.bench}/meta_features.csv
  lc_meta: ${dataset.preprocessed_path}/${dataset_raw.selection.bench}/logs_subset.h5

split: 0.8

slices: [ 0.1, 0.3, 0.5, 1. ] #[ 1, 10, 20, 51 ] lcbench
metric: acc

# fixme: remove legacy
lc_metric: None