name: yahpo
preprocessed_path: ../../../data/raw/${dataset.name}

path:
  algo_meta: ${dataset.preprocessed_path}/${dataset_raw.selection.bench}/config_subset.csv
  data_meta: ${dataset.preprocessed_path}/${dataset_raw.selection.bench}/meta_features.csv
  lc_meta: ${dataset.preprocessed_path}/${dataset_raw.selection.bench}/logs_subset.h5

split: 0.8

slices: [ 1, 10, 20, 51 ]
metric: val_cross_entropy

# fixme: remove legacy
lc_metric: None