# FIXME: make this dependent on the output from the raw transformation
name: LCBench
preprocessed_path: ./data/raw/${dataset.name}  # fixme: is raw what we are going for?

path:
  algo_meta: ${dataset.preprocessed_path}/config_subset.csv
  data_meta: ${dataset.preprocessed_path}/meta_features.csv
  lc_meta: ${dataset.preprocessed_path}/logs_subset.h5

lc_metric: Train/val_accuracy # to be extracted & used (see dataset_raw/lcbench for options)
split: 0.8

# fixme: move dataset_class & dataloader_class to a level up! (as it is used in both datasets)
dataset_class:
  _target_: imfas.data.Dataset_Join_Dmajor
  meta_dataset: ${dataset.dataset_meta}
  lc: ${dataset.lc_meta}
  #      meta_algo: dataset.algo_meta

# fixme: refactor this to be separately configurable at will for train/test
dataloader_class:
  _target_: torch.utils.data.DataLoader
  batch_size: ${test_batch_size}
  shuffle: False
  num_workers: ${num_workers}

slices:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  - 24
  - 25
  - 26
  - 27
  - 28
  - 29
  - 30
  - 31
  - 32
  - 33
  - 34
  - 35
  - 36
  - 37
  - 38
  - 39
  - 40
  - 41
  - 42
  - 43
  - 44
  - 45
  - 46
  - 47
  - 48
  - 49
  - 50
  - 51