defaults:
  - dataset_meta: lcbench_minimal
  - lc_meta: multi_slice


name: lcdb



path:
  data_meta: ${dir_data_processed}/lcdb/dataset_meta_features.csv
  lc_meta: ${dir_data_processed}/lcdb #/${dataset.dataset_raw.selection.bench}/logs_subset.h5


slices: [ 16, 23, 32, 45, 64, 91, 128, 181, 256, 362, 512, 724, 1024, 1448, 2048, 2588 ] # ${range:0.1, 1.1, 0.1} fixme: check if that worked!

dataset_raw:
  _target_: imfas.data.lcdb.raw_pipe.raw_pipe
  enable: True
  path_preprocessed: ${dir_data_processed}/lcdb

  slices: ${dataset.slices}
  metric: accuracy  # options ["accuracy", "logloss", "f1", "auc"]  # all of which are test