_target_: mf_gravitas.data.lcbench.raw_pipe.raw_pipe
dataset_name: LCBench

#TODO Change to relative
dir_data: ../../../data/
extract: data_2k  # json file
enable: False # whether to override the preprocessing
re_download: False
reload_from_downloads: False # will override the '*subset' files




selection:
  metric: final_test_cross_entropy
  # options :
  #       'model_parameters', 'final_train_cross_entropy', 'final_train_accuracy',
  #       'final_train_balanced_accuracy', 'final_val_cross_entropy',
  #       'final_val_accuracy', 'final_val_balanced_accuracy',
  #       'final_test_cross_entropy', 'final_test_accuracy',
  #       'final_test_balanced_accuracy', 'OpenML_task_id', 'test_split',
  #       'budget', 'seed', 'instances', 'classes', 'features'

  algo: # fixme: move this to separate yaml
    _target_: mf_gravitas.data.ensemble.topk.ensemble
    k: 3

learning_curves:
  metrics:
    - Train/loss
    - Train/lr
    - Train/test_balanced_accuracy
    - Train/test_cross_entropy
    - Train/test_result
    - Train/train_accuracy
    - Train/train_balanced_accuracy
    - Train/train_cross_entropy
    - Train/val_accuracy
    - Train/val_balanced_accuracy
    - Train/val_cross_entropy
    - epoch
    - time

    # options:
    #       'Train/loss', 'Train/lr',
    #       'Train/test_balanced_accuracy', 'Train/test_cross_entropy',
    #       'Train/test_result', 'Train/train_accuracy',
    #       'Train/train_balanced_accuracy', 'Train/train_cross_entropy',
    #       'Train/val_accuracy', 'Train/val_balanced_accuracy',
    #       'Train/val_cross_entropy', 'epoch', 'time'
    #       'Train/gradient_max', 'Train/gradient_mean', 'Train/gradient_median',
    #       'Train/gradient_norm', 'Train/gradient_q10', 'Train/gradient_q25',
    #       'Train/gradient_q75', 'Train/gradient_q90', 'Train/gradient_std',
    #       'Train/layer_wise_gradient_max_layer_0',
    #       'Train/layer_wise_gradient_max_layer_1',
    #       'Train/layer_wise_gradient_max_layer_2',
    #       'Train/layer_wise_gradient_max_layer_3',
    #       'Train/layer_wise_gradient_mean_layer_0',
    #       'Train/layer_wise_gradient_mean_layer_1',
    #       'Train/layer_wise_gradient_mean_layer_2',
    #       'Train/layer_wise_gradient_mean_layer_3',
    #       'Train/layer_wise_gradient_median_layer_0',
    #       'Train/layer_wise_gradient_median_layer_1',
    #       'Train/layer_wise_gradient_median_layer_2',
    #       'Train/layer_wise_gradient_median_layer_3',
    #       'Train/layer_wise_gradient_q10_layer_0',
    #       'Train/layer_wise_gradient_q10_layer_1',
    #       'Train/layer_wise_gradient_q10_layer_2',
    #       'Train/layer_wise_gradient_q10_layer_3',
    #       'Train/layer_wise_gradient_q25_layer_0',
    #       'Train/layer_wise_gradient_q25_layer_1',
    #       'Train/layer_wise_gradient_q25_layer_2',
    #       'Train/layer_wise_gradient_q25_layer_3',
    #       'Train/layer_wise_gradient_q75_layer_0',
    #       'Train/layer_wise_gradient_q75_layer_1',
    #       'Train/layer_wise_gradient_q75_layer_2',
    #       'Train/layer_wise_gradient_q75_layer_3',
    #       'Train/layer_wise_gradient_q90_layer_0',
    #       'Train/layer_wise_gradient_q90_layer_1',
    #       'Train/layer_wise_gradient_q90_layer_2',
    #       'Train/layer_wise_gradient_q90_layer_3',
    #       'Train/layer_wise_gradient_std_layer_0',
    #       'Train/layer_wise_gradient_std_layer_1',
    #       'Train/layer_wise_gradient_std_layer_2',
    #       'Train/layer_wise_gradient_std_layer_3'