# @package _global_

defaults:
  - dataset_raw: lcbench
  - dataset: lcbench
  # - dataset/algo_meta: lcbench_minimal
  - dataset/dataset_meta: lcbench_minimal
  - dataset/lc_meta: multi_slice
  - model: rank_ensemble
  - training: freeze_ensemble # ensemble

  - _self_ # at the end means overriding values of lower yaml here!


seed: 0
output_dir: ./tmp


num_competitors: 1 # fixme: move me to autoencoder
num_workers: 2
train_batch_size: 1
test_batch_size: 1

lr: 0.001  # fixme: move learning rate of the train's optimizer
shuffle: True

wandb:
  id: null
  entity: tnt
  project: gravitas
  mode: 'offline'    # Change to offline or debug mode
  job_type: train
  tags: [ ]
  notes: null
  group: null
  sync_tensorboard: False
  save_code: False
  resume: 'allow'

hydra:
  run:
    dir: ${output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}