agent:
  nA: 0           # Initially set to 0, changed in ingestion
  seed: 123546
  root_dir: ''
  suggest_topk: 2
  encoder: 'AE'
  
  AE:
    _target_: mf_gravitas.src.models.autoencoder.AE
    input_dim: 10
    embedding_dim: 2
    hidden_dims: [8, 4]
    weights: [1., 1., 1., 1.]
    repellent_share: 0.33
    n_algos: 20
    device: 'cpu'

