defaults:
  - dataset_raw: lcbench
  - dataset: lcbench
  - model: autoencoder
  - evaluation: optimal_rankings
  - training: sequential
  - _self_ # at the end means overriding values of lower yaml here!


seed: 0
output_dir: ./tmp


num_competitors: 2
num_workers: 2
train_batch_size: 4
test_batch_size: 20

lr: 0.002   # learning rate of the train's optimizer
shuffle: True

wandb:
  id: null
  entity: tnt
  project: gravitas
  mode: 'online'    # Change to offline or debug mode
  job_type: train
  tags: []
  notes: null
  group: null
  sync_tensorboard: False
  save_code: False
  resume: 'allow'