# @package _global_

defaults:
  - dataset_raw: lcbench
  - dataset: lcbench
  - model: autoencoder
  - evaluation: optimal_rankings
  - training: gravity
  - slurm
  - _self_ # at the end means overriding values of lower yaml here!

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

seed: 0
output_dir: ./tmp


num_competitors: 11
num_workers: 2
train_batch_size: 10
test_batch_size: 10

lr: 0.001  # learning rate of the train's optimizer
shuffle: True

wandb:
  id: null
  entity: tnt
  project: gravitas
  mode: 'online'    # Change to offline or debug mode
  job_type: train
  tags: []
  notes: null
  group: null
  sync_tensorboard: False
  save_code: False
  resume: 'allow'

hydra:
  run:
    dir: ${output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}