dataset:
  name: lcbench
  n_algos: ???
  n_datasets: ???  # FIXME: make this dependent on the output from the raw transformation

  preprocessed_path: /some/path

  dataset_meta_features:
    # path: some/path - we might want to automate and structure it
    transforms:
      - some_class
        columns: [ 'a', 'b' ]
      - some_class
        columns: [ 'c' ]

  algo_meta_features:
    # path: some/path - we might want to automate and structure it
    transforms:
    # just like above

  learning_curves:
    transforms:
    # just like above

  learning_curves_final:
    transform:
    # just like the others
