model:
  _target_: mf_gravitas.models.autoencoder.ParticleGravityAutoencoder
  input_dim: 27
  hidden_dims: [8, 4]
  embedding_dim: 2
  weights: [1.0, 1.0, 1.0, 1.0]
  repellent_share: 0.33
  n_algos: 20
  device: 'cpu'