# FIXME: make this dependent on the output from the raw transformation

preprocessed_path: /some/path

dataset_meta_features:
  _target_: src.data.preprocessings.transformpipeline.TransformPipeline
  # path: some/path - we might want to automate and structure it
  transforms: None
  # just like above

algo_meta_features:
  _target_: src.data.preprocessings.transformpipeline.TransformPipeline
  # path: some/path - we might want to automate and structure it
  modulelist:
    - _target_: src.data.preprocessings.table_transforms.Drop
      columns:
        - 'imputation_strategy'
        - 'learning_rate_scheduler'
        - 'loss'
        - 'network'
        - 'normalization_strategy'
        - 'optimizer'
        - 'activation'
        - 'mlp_shape'
    - _target_: src.data.preprocessings.table_transforms.Replace
      columns:
        - 'num_layers'
      replacedict: { 'True': 1 }
    - _target_: src.data.preprocessings.table_transforms.Convert
      columns:
        - 'num_layers'
      dtype: 'numeric'
    - _target_: src.data.preprocessings.table_transforms.ToTensor




learning_curves:
  _target_: src.data.preprocessings.transformpipeline.TransformPipeline
  transforms:
  # just like above


