name: Tests

on:
  # Allow to manually trigger through github API
  workflow_dispatch:

  # Triggers with push to main
  push:
    branches:
      - main
      - development

  # Triggers with push to a PR aimed at main
  pull_request:
    branches:
      - main
      - development

  schedule:
    # Every day at 7AM UTC
    - cron: '0 07 * * *'

env:

  package-name: masif
  test-dir: tests
  extra-requires: "[dev]"  # "" for no extra_requires

  # Arguments used for pytest
  pytest-args: >-
    --durations=20
    -v

jobs:

  # General unit tests
  source-test:
    name: ${{ matrix.python-version }}-${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: ["ubuntu-latest"]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install ${{ env.package-name }}
      run: |
        pip install wheel
        pip install -e ".${{ env.extra-requires }}"

    - name: Tests
      run: |
        pytest ${{ env.pytest-args }} ${{ env.test-dir }}
